### ISSUE TITLE
Add `update_config` and deprecate `reload_config`

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-protocol#28]
I think central management server now has full configuration of agents, and the server notifies agents to fetch the newly updated configuration. So I thought we might need a function in `request::Handler`, such as `async fn notify_config_change(&mut self) -> Result<(), String>`. And I also think that we no longer need the existing `async fn reload_config(&mut self) -> Result<(), String>` function, because I understood one of the main points of recent changes is that the central server only "notifies" agents, not directly requesting the reload. So I think we can rename the `reload_config` to `notify_config_change`, because they only differ in name. Could maintainers or anyone check if this is okay please? (I wanted to write this in discussions tab, but I cannot see it in this repository, so I used a prefix in the title).

**Comment by msk** [comment]
Thank you for your thoughtful suggestion. Based on your proposal and after consideration, I suggest the following changes:

1. Add a new method to the `Handler` trait:
   ```rust
   async fn update_config(&mut self) -> Result<(), String>
   ```
   This method aligns with the new architecture where agents are responsible for updating their configuration based on notifications from the central server.

2. Deprecate the existing `reload_config` method:
   ```rust
   #[deprecated(since = "x.y.z", note = "Use update_config instead")]
   async fn reload_config(&mut self) -> Result<(), String>
   ```
   This approach maintains backwards compatibility while signaling the direction of future changes.

I chose `update_config` instead of `notify_config_change` for a few reasons:
- It maintains consistency with the existing naming convention in the `Handler` trait, where method names describe actions from the agent's perspective.
- It clearly indicates the action the agent should take (updating its configuration).
- It aligns with the new workflow where agents are responsible for fetching and applying configuration updates.

This approach allows us to transition to the new architecture while maintaining API consistency and providing a clear upgrade path for developers.

I'm open to further discussion on this topic. What are your thoughts on this proposed solution?

**Comment by sophie-cluml** [comment]
It sounds good. Thank you for your answer. 
Let me turn this into an issue and make the changes.
